# https://taskfile.dev

version: '3'

vars:
  IMAGE_FILE: image.txt

dotenv: ['.env']

tasks:

  lint:
    desc: Runs the linters and formatters
    cmds:
      - golangci-lint run --fix .
      - golines --no-reformat-tags -w .
      - golangci-lint run

  audit:
    desc: Checks for security issues
    cmds:
      - go vet ./...
      - staticcheck ./...
      - govulncheck


  build:
    desc: Build & publish image
    deps: [lint,audit]
    cmds:
      - KO_DOCKER_REPO=registry.fly.io/$FLY_APP_NAME  ko build . --bare --platform=linux/amd64 > {{.IMAGE_FILE}}
    sources:
      - '**/*.go'
      - 'go.mod'
    generates:
      - '{{.IMAGE_FILE}}'

  deploy:
    desc: Deploy to fly
    deps: [build]
    cmds:
      - fly deploy -a $FLY_APP_NAME  -i {{.IMAGE}}
    sources:
      - '{{.IMAGE_FILE}}'
    vars:
      IMAGE:
        sh: cat {{.IMAGE_FILE}}

  clean:
    desc: Clean every generated file
    cmds:
      - rm -f {{.IMAGE_FILE}}
